version: '3.8'
services:
  main:
    build: ./main/
    image: "main_image"
    container_name: "main_container"
    ports:
      - "8080:8080"
    depends_on:
      - stats
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/explorewithme
      - STATS_URL=http://stats:9090

  stats:
    build: ./stats/
    image: "stats_image"
    container_name: "stats_container"
    ports:
      - "9090:9090"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/explorewithme

  db:
    image: postgres:13.7-alpine
    container_name: "db_container"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=explorewithme
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root